package fr.herobrine.autospeller.client.rendering

import fr.herobrine.autospeller.client.linting.ChatLintingSession
import fr.herobrine.autospeller.linting.TextSuggestion

/**
 * Rendering ticket, that can then be submitted to the [ChatRenderer].
 *
 * The ticket holds de session, along with the suggestions generated by the [fr.herobrine.autospeller.service.InputProcessor].
 */
data class ChatRenderingTicket(
    val lintingSession: ChatLintingSession,
    val textSuggestions: List<TextSuggestion>,
    )
